projectcbv/cbvapp/urls.py
from django.urls import path
from . import views

app_name = "cbvapp"


urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path('<pk>/', views.SchoolDetailView.as_view(),name='detail'),
    path('create/', views.SchoolCreateView.as_view(),name='create'),
    path('update/<pk>/', views.SchoolUpdateView.as_view(), name='update'),
    path('create_car/', views.CarCreateView.as_view(), name='create_car'),
    
]

projectcbv/projectcbv/urls.py
from django.contrib import admin
from django.urls import path,include
from cbvapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),
    path('cbvapp/', include('cbvapp.urls'),name="cbvapp"),
]

projectcbv/cbvapp/models.py
from django.db import models
from django.urls import reverse

class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)
    
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("cbvapp:detail", kwargs={"pk": self.pk})


class Car(models.Model):
    brand = models.CharField(max_length=256)
    license_plate = models.CharField(max_length=256)
    manufacturing_year = models.PositiveIntegerField()
    
    
    def __str__(self):
        return self.brand
    
    # def get_absolute_url(self):
    #     return reverse("cbvapp:detail", kwargs={"pk": self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)
    
    
    def __str__(self):
        return self.name

projectcbv/cbvapp/views.py
from django.shortcuts import render
from django.views.generic import (View,
                                  TemplateView,
                                  ListView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView)



from . import models


class IndexView(TemplateView):
    template_name = 'index.html'


class SchoolListView(ListView):
    context_object_name = "schools"
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = "school_detail"
    model = models.School
    template_name = 'cbvapp/school_detail.html'

class SchoolCreateView(CreateView):
    model = models.School
    fields = ["name","principal","location"]
    

class SchoolUpdateView(UpdateView):
    fields = ['name','principal','location']
    model = models.School

class CarCreateView(CreateView):
    model = models.Car
    fields = ["brand","license_plate","manufacturing_year"]
    

projectcbv/cbvapp/templates/cbvapp/car_form.html
{% extends 'cbvapp/cbvapp_base.html' %}



{% block body_block %}

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>


{% endblock %}

projectcbv/cbvapp/templates/cbvapp/cbvapp_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Base</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'cbvapp:list' %}">Schools</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a href="#"></li>

        </ul>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

projectcbv/cbvapp/templates/cbvapp/school_detail.html
{% extends 'cbvapp/cbvapp_base.html' %}
{% block body_block %}

<div class="align center">
    <h1>Welcome to the school detail page</h1>
    <h2>School details: </h2>
    <p>Name: {{school_detail.name}}</p>
    <p>Principal: {{school_detail.principal}}</p>
    <p>Location: {{school_detail.location}}</p>
    <h3>Students</h3>

    {% for student in school_detail.students.all %}
    <p>{{student.name}} who is {{student.age}} years old.</p>
    {% endfor %}
    
</div>
<div class="container">
    <p>
        <h1>{{school_detail.pk}}</h1>
        <a class="btn btn-warning" href="{% url 'cbvapp:update' pk=school_detail.pk %}">Update</a>
    </p>

</div>


{% endblock %}

projectcbv/cbvapp/templates/cbvapp/school_form.html
{% extends 'cbvapp/cbvapp_base.html' %}

{% block body_block %}

<h1>
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {% endif %}
    
</h1>

<form method="post">{% csrf_token %}
    {% for field in form %}
        <div class="fieldWrapper">
            {{ field.errors }}
            {{ field.label_tag }}
            {{ field }}
        </div>
    {% endfor %}
    <p><input type="submit" class="btn btn-primary" value="submit"></p>
</form>






{% endblock %}

projectcbv/cbvapp/templates/cbvapp/school_list.html
{% extends "cbvapp/cbvapp_base.html" %}

{% block body_block %}

<h1>Welcome to a list of all the schools</h1>
<ol>
    {% for school in schools %}
    <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
    {% endfor %}
</ol>

{% endblock %}

projectcbv/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Base</title>
</head>
<body>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
    
</body>
</html>

projectcbv/templates/index.html
{% extends "base.html" %}
{% block body_block %}
<h1>Home Page</h1>
{% endblock %}